# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Modified Java CI with Maven
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-latest
        java-version:
          - 11.0.3
          - 11
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: zulu
      - name: Build with Maven
        run: mvn -B package --file pom.xml "-Dmaven.surefire.skipTests=false" "-Dmaven.surefire.reportsDirectory=target/surefire-reports"
          "-Dmaven.surefire.forkMode=once"
    name: build (${{ matrix.os }}, ${{ matrix.java-version }})
'on':
  - push
  - workflow_dispatch
